accounts/urls.py
from django.urls import path

from .views import UserSubscriptionView, CancelSubscriptionView

app_name="accounts"

urlpatterns = [
    path("<str:username>/profile/", UserSubscriptionView.as_view(), name="profile"),
    path("<str:username>/profile/cancel/", CancelSubscriptionView.as_view(), name="cancel-subscription"),
]

core/urls.py
import imp
from django.urls import path
from core import views

urlpatterns = [
    path('', views.index, name="home"),
    path('agendar',views.schedule,name="schedule"), 
    path('agendar/sets/<slug:slug>/',views.sets,name="set"),
    path('nuestros-trabajos',views.works,name="works"), 
    path('cursos',views.courses,name="courses"), 
    path('cursos/<slug:slug>/',views.courses_view,name="course_view"),
    path('prices/',views.pricesView,name="prices"), 
    path('payment/<slug:slug>',views.paymentsView,name="payment"),
    path('payment/create-subscription/', views.CreateSubscriptionView.as_view(), name='create-subscription'),
    path('payment/thank-you/',views.ThankYouView,name="thank-you"), 
    path('payment/retry-invoice/', views.RetryInvoiceView.as_view(), name='retry-invoice'),
    path('change-subscription/', views.ChangeSubscriptionView.as_view(), name='change-subscription'),
    path('payment/webhook/', views.webhook, name='webhook'),

    path('cursos/<slug:slug>/<int:chapter_number>/', views.get_data_ajax, name='ajax')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('accounts.urls',namespace="user")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.page_not_found'

templates/fragments/navbar.html
<header class="content-head">
        
    <div class="main-menu">
        {% for header in headers %}
        <div class="logo">
            <button class="button btn-menu" onclick="window.location.href='{% url 'home' %}';">
                <img src="{{header.logo.url}} " alt="">
            </button>

        </div>
        {%endfor%}
        <div class="button-divs">
            <div>
                <button class="button btn-menu" onclick="window.location.href='{% url 'schedule' %}';">
                    Agendar Sesion
                </button>
            </div>
            <div>
                <button class="button btn-menu" onclick="window.location.href='{% url 'works' %}';">
                    Nuestros Trabajos
                </button>
            </div>
            {% for header in headers %}
            <div>
                <button class="button btn-menu"
                    onclick="location.href='https://api.whatsapp.com/send?phone=+{{header.number}}&text=Hola%20Mtask%20Studio.%20Me%20interesa%20contratarlos.';">
                    <i class="fa-solid fa-phone"></i>
                </button>
            </div>
            {%endfor%}
            {% if user.is_authenticated %}
            
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="photografy_profile" style="background-image: url({{user.perfil_photo.url}});"></div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu" style="width:200px">
                    <li class="user_fullname">{{user.full_name}}</li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'user:profile' user.username %}">Ver Perfil</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Salir</a></li>
                  </ul>
              </div>
            {% else %}
            <div>
                <button class="button btn-menu" onclick="window.location.href='{% url 'account_login' %}';">
                    <i class="fa-solid fa-user"></i>
                </button>
            </div>
            {% endif %}
        </div>
    </div>
</header>