accounts/urls.py
from django.urls import path

from .views import UserSubscriptionView, CancelSubscriptionView

app_name="accounts"

urlpatterns = [
    path("<str:username>/profile/", UserSubscriptionView.as_view(), name="profile"),
    path("<str:username>/profile/cancel/", CancelSubscriptionView.as_view(), name="cancel-subscription"),
]

core/urls.py
import imp
from django.urls import path
from core import views

urlpatterns = [
    path('', views.index, name="home"),
    path('agendar',views.schedule,name="schedule"), 
    path('agendar/sets/<slug:slug>/',views.sets,name="set"),
    path('nuestros-trabajos',views.works,name="works"), 
    path('cursos',views.courses,name="courses"), 
    path('cursos/<slug:slug>/',views.courses_view,name="course_view"),
    path('prices/',views.pricesView,name="prices"), 
    path('payment/<slug:slug>',views.paymentsView,name="payment"),
    path('payment/create-subscription/', views.CreateSubscriptionView.as_view(), name='create-subscription'),
    path('payment/thank-you/',views.ThankYouView,name="thank-you"), 
    path('payment/retry-invoice/', views.RetryInvoiceView.as_view(), name='retry-invoice'),
    path('change-subscription/', views.ChangeSubscriptionView.as_view(), name='change-subscription'),
    path('payment/webhook/', views.webhook, name='webhook'),

    path('cursos/<slug:slug>/<int:chapter_number>/', views.get_data_ajax, name='ajax')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('accounts.urls',namespace="user")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.page_not_found'

templates/users/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center; margin-top: 120px;">
    <h1>Datos del Perfil</h1>
</div>
<hr>
<div class="sessions-wrapper">
    <div class="view-profile-info">
        <div class="image-content">
            <div class="photografy_profile img-profile" style="background-image: url({{user.perfil_photo.url}});"></div>
        </div>
        <div class="data-profile">
            <p><span>Nombre Completo:</span> {{user.full_name}}</p>
        </div>
    </div>
    <div class="profile-options">2</div>
    {% if user.subscription.pricing.name != "Free" %}
    {% if user.subscription.status != "canceled"%}
    {% if user.subscription.pricing.name != "" %}
    <form method="post" class="py-3 mt-3 inline-flex float-right"
        action="{% url 'user:cancel-subscription' request.user.username %}">
        {% csrf_token %}
        {{ form }}
        <button
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
            type="submit">
            Cancelar Subscripcion
        </button>
    </form>
    {% endif %}
    {% endif %}
    {% endif %}
</div>
{% endblock %}

{% block extra_js %}
<script>
    var ancho = $(".img-profile").width()
    $(".img-profile").css("height",ancho)
    $( window ).resize(function() {
        var ancho = $(".img-profile").width()
    $(".img-profile").css("height",ancho)
});
    
</script>
{% endblock %}